# Useful for testing
# Should give between 55 and 60 MRR 

1toN:
  label_smoothing: -1.0
ax_search:
  num_trials: 50
  num_sobol_trials: 10 
  #gpei_trials: 40 
  parameters:
  - name: train.max_epochs
    type: fixed
    value: 50
  - name: train.optimizer
    type: fixed
    value: Adagrad
  - name: train.batch_size
    type: fixed
    value: 512
  - bounds:
    - 0.0
    - 1.0
    name: train.optimizer_args.lr
    type: range
  - name: complex.entity_embedder.dim
    type: fixed
    value: 50
  - name: complex.entity_embedder.regularize
    type: fixed
    value: l2
  - bounds:
    - 1.0e-12
    - 1.0e-05
    log_scale: true
    name: complex.entity_embedder.regularize_weight
    type: range
  - bounds:
    - 0.0
    - 0.5
    name: complex.entity_embedder.dropout
    type: range
  - name: complex.relation_embedder.dim
    type: fixed
    value: 50
  - name: complex.relation_embedder.regularize
    type: fixed
    value: l2
  - bounds:
    - 1.0e-12
    - 1.0e-05
    log_scale: true
    name: complex.relation_embedder.regularize_weight
    type: range
  - bounds:
    - 0.0
    - 0.5
    name: complex.relation_embedder.dropout
    type: range
checkpoint:
  every: 5
complex:
  auto_initialization: true
  class_name: ComplEx
  entity_embedder:
    +++: +++
    dim: 50
    dropout: 0.24882794967985034
    regularize: l2
    regularize_weight: 3.848163813697466e-10
    type: lookup_embedder
  relation_embedder:
    +++: +++
    dim: 50
    dropout: 0.031805645363255364
    regularize: l2
    regularize_weight: 8.981610829738733e-08
    type: lookup_embedder
dataset:
  entity_map: entity_map.del
  name: toy
  relation_map: relation_map.del
  test: test.del
  train: train.del
  valid: valid.del
eval:
  batch_size: 100
  data: valid
  hits_at_k_s: [1, 3, 10]
  num_workers: 0
  pin_memory: false
  trace_level: example
  type: entity_ranking
grid_search:
  parameters:
    +++: +++
  run: true
import: complex
job:
  device: cpu
  type: train
lookup_embedder:
  class_name: LookupEmbedder
  dim: 100
  dropout: 0.0
  initialize: normal_
  initialize_args:
    +++: +++
  #normalize:
  #  +++: +++
  regularize: l2
  regularize_weight: 0.0
  sparse: false
manual_search:
  configurations: []
  run: true
model: complex
negative_sampling:
  #filter_negatives: false
  num_negatives_o: -1
  num_negatives_p: 0
  num_negatives_s: 3
  sampling_type: uniform
search:
  num_workers: 1
  type: ax
train:
  batch_size: 512
  loss: bce
  loss_arg: 1.0
  max_epochs: 50
  num_workers: 0
  optimizer: Adagrad
  optimizer_args:
    +++: +++
    lr: 0.9880936573436668
  pin_memory: false
  trace_level: epoch
  type: 1toN
  auto_correct: true
user:
  +++: +++
valid:
  #early_stopping: 
  #  +++: +++
  every: 5
  filter_with_test: true
  metric: mean_reciprocal_rank_filtered_with_test
  metric_expr: ''
  trace_level: epoch
