job.type: train
dataset.name: fb15k-237
# dataset.name: toy

model: sparse_relational_tucker3

sparse_relational_tucker3:
  entity_embedder:
    type: lookup_embedder
    dropout: 0.4
    dim: 200
    initialize: normal
    initialize_arg: 0.1
  relation_embedder:
    base_embedder:
      dim: 160
      dropout: 0.0
    dropout: 0.0
    initialize: normal
    initialize_arg: 0.001
    l0_weight: 1e-3
    # l0_weight: 5e-11 # l0_lambda = 0.1
                             # -> l0_reg = l0_lambda / (|entities| * |train data|)
                             #  = 0.1 x 5e-10
    # loc_mean: 3.
    # loc_sdev: 1.

train:
  batch_size: 512
  max_epochs: 50
  optimizer: Adagrad
  optimizer_args:
    lr: 0.05
    weight_decay: 0

valid:
  filter_with_test: True

eval:
  batch_size: 512
