job.type: train
dataset.name: fb15k-237
model: complex
complex:
  entity_embedder.dropout: 0.4
  relation_embedder.dropout: 0.0

lookup_embedder:
  dim: 200
  initialize: normal
  initialize_arg: 0.1

train:
  max_epochs: 20
  optimizer: Adagrad
  batch_size: 512
  optimizer_args:
    lr: 0.3
    weight_decay: 1e-10

valid:
  filter_with_test: True

eval.batch_size: 1024
