job.type: train
dataset.name: toy
model: complex
train:
  type: negative_sampling
  num_negatives: 3
  optimizer: Adagrad
  optimizer_args:
    lr: 0.2
    weight_decay: 0.4e-7
lookup_embedder.dim: 100
