job.type: train
dataset.name: toy
model: inverse_relations_model
inverse_relations_model.base_model.type: conve # redundant since also default
train:
  optimizer: Adam
  optimizer_args:
    lr: 0.2
    weight_decay: 0.4e-7
lookup_embedder.dim: 200
lookup_embedder.initialize: xavier_normal_
