job.type: train
dataset.name: toy
model: transe

transe:
  entity_embedder:
    dim: 200
    normalize: 'L2'
    regularize: ''
  relation_embedder:
    dim: 200
    normalize: ''
    regularize: ''

train:
  type: negative_sampling
  optimizer: Adagrad
  optimizer_args:
    lr: 0.1
  loss: margin_ranking
  loss_arg: 1.0  # margin
negative_sampling:
  num_negatives_s: 3
  sampling_type: uniform
  filter_negatives: False

