dataset:
  entity_map: entity_map.del
  name: toy
#  name: fb15k-237
  relation_map: relation_map.del
  test: test.del
  train: train.del
  valid: valid.del

job:
  device: cuda
  type: search

checkpoint:
  every: 5

1toN:
  label_smoothing: -1.0

train:
  batch_size: 512
  loss: bce
  lr_scheduler: ConstantLRScheduler
  max_epochs: 200
  num_workers: 0
  optimizer: Adagrad
  optimizer_args:
    +++: +++
    lr: 0.1
  pin_memory: false
  trace_level: epoch
  type: 1toN
  auto_correct: true

negative_sampling:
  num_negatives_o: -1
  num_negatives_p: 0
  num_negatives_s: 16
  sampling_type: uniform

user:
  +++: +++

valid:
  early_stopping:
    min_threshold:
      epochs: 25
      metric_value: 0.05
    patience: 6
  every: 5
  filter_with_test: true
  metric: mean_reciprocal_rank_filtered_with_test
  metric_expr: ''
  trace_level: epoch

eval:
  batch_size: 100
  data: valid
  num_workers: 0
  pin_memory: false
  trace_level: example
  type: entity_ranking

import: sd_rescal
model: sd_rescal

sd_rescal:
  class_name: SparseDiagonalRescal
  blocks: 4
  block_size: 32
  entity_embedder:
    type: lookup_embedder
    dropout: 0.2
  relation_embedder:
    type: lookup_embedder
    dropout: 0.2

search:
  num_workers: 1
  type: ax

ax_search:
  num_trials: 20
  num_sobol_trials: 10
  parameters:
  - is_ordered: true
    name: train.batch_size
    type: choice
    values: [256, 512, 1024]
  - {name: train.type, type: fixed, value: 1toN}
  - name: train.optimizer
    type: choice
    values: [Adam, Adagrad]
  - {name: train.loss, type: fixed, value: bce}
  - bounds: [0.0003, 1.0]
    log_scale: true
    name: train.optimizer_args.lr
    type: range
  - {name: train.lr_scheduler, type: fixed, value: ReduceLROnPlateau}
  - {name: train.lr_scheduler_args.mode, type: fixed, value: max}
  - bounds: [1, 10]
    name: train.lr_scheduler_args.patience
    type: range
  - bounds: [-0.3, 0.3]
    name: 1toN.label_smoothing
    type: range
  - name: lookup_embedder.regularize
    type: choice
    values: ['', l3, l2, l1 ]
    is_ordered: true
  - bounds: [1.0e-20, 1.0e-05]
    log_scale: true
    name: lookup_embedder.regularize_args.weight
    type: range
  - bounds: [-0.5, 0.5]
    name: sd_rescal.entity_embedder.dropout
    type: range
  - bounds: [-0.5, 0.5]
    name: sd_rescal.relation_embedder.dropout
    type: range
  - {name: sd_rescal.auto_initialization, type: fixed, value: true}
  - name: sd_rescal.blocks
    type: range
    bounds: [2, 10]
  - name: sd_rescal.block_size
    type: choice
    values: [16, 32, 48, 64, 80, 96, 112, 128, 256]
    is_numerical: True
    is_ordered: True

search.num_workers: 2
train.num_workers: 2
eval.num_workers: 2