job.type: train
#dataset.name: toy
model: complex

train:
  type: negative_sampling
  optimizer: Adagrad
  optimizer_args:
    lr: 0.2
    weight_decay: 0.4e-7
  loss: margin_ranking
#  loss: bce
  loss_arg: 2.0  # margin
  batch_size: 512

lookup_embedder.dim: 100

negative_sampling:
  num_negatives_s: 1000
  num_negatives_o: -1
