job.type: train
dataset.name: toy
model: relational_tucker3

relational_tucker3:
  entity_embedder:
    dim: 100
    dropout: 0.1
  relation_embedder:
    base_embedder:
      dim: 100
      dropout: 0.1
    dropout: 0.1

train:
  optimizer: Adagrad
  optimizer_args:
    lr: 0.2
    weight_decay: 0.4e-7
