dataset:
  name: 'toy'
  train: train.del            # entries: s<tab>p<tab>o<tab>metadata
  valid: valid.del            # entries: s<tab>p<tab>o<tab>metadata
  test: test.del              # entries: s<tab>p<tab>o<tab>metadata
  entity_map: entity.del      # entries: s<tab>metadata
  relation_map: relation.del    # entries: p<tab>metadata

model:
  name: complex               # distmult, complex, transe, conve
  dim: 200                    # entity dimensionality

output:
  folder: ''                  # '' means: local/experiments/<date>-<dataset>-<model>
  subfolder: ''               # '' means none; overwritten e.g. by grid search
  logfile: 'kge.log'
  resume: false

train:
  max_epochs: 20
  type: 1toN                  # 1toN, negative_sampling
  optimizer: adagrad          # sgd, adagrad, adam
  batch_size: 100
  lr: 0.01
  l2_reg: 0.0001
  init: uniform               # uniform, xavier, he

validate:
  every: 5                    # epochs (disable with 0)
  early_abort: False

evaluate:
  type: entity_ranking        # or pair-ranking
  k: 10                       # maximum k for hits@k

# TODO grid-search here? -> changes other configuration paramters in some
# systmatic way (including output fold)
# search:
#   type: grid train.lr
#   lr: = [ 0.01, 0.001 ]

# TODO checkpointing
# checkpoint:
#   every: 0                    # epochs (disable with 0)

# TODO model-specific parametrs
# SRT:
#   rel_dim: 200
